### ISSUE TITLE
Error when trying to compile Duckyscript

### ISSUE THREAD

**Issue by matty0005** [uslurper/digiduck#1]
C:\Users\USER\Documents\Hacking\Digispark>digiduck DNSPoison.txt DnsPoisonDigi
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\digiduck.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\digiduck\__init__.py", line 26, in main
    x = parseseq(tokens)
  File "c:\python27\lib\site-packages\digiduck\dparser.py", line 137, in parseseq
    for j in range(lcount):
UnboundLocalError: local variable 'lcount' referenced before assignment

**Comment by uslurper** [comment]
Whoops. Well, thank you for letting me know about the error, I'll have it patched in no time.

**Comment by uslurper** [comment]
Done. Thank you for your feedback.
