### ISSUE TITLE
Error using Windows

### ISSUE THREAD

**Issue by SamGurdus1** [uslurper/digiduck#4]
I installed it using pip, but when attempting to use the command, 
digiduck C:\Users\Sam\Desktop\source.txt C:\Users\Sam\Desktop\dest.txt
I'm getting this error

Traceback (most recent call last):
  File "c:\users\sam\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sam\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python37-32\Scripts\digiduck.exe\__main__.py", line 5, in <module>
  File "c:\users\sam\appdata\local\programs\python\python37-32\lib\site-packages\digiduck\__init__.py", line 11
    print "DIGIDUCK: Ducky Script to Digispark compiler"
                                                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("DIGIDUCK: Ducky Script to Digispark compiler")?

**Comment by uslurper** [comment]
Hello,
Digiduck.py was written using Python 2.7. Attempting to run it with Python 3 will lead to errors like this. I plan on refactoring the code for Python 3 (as well as adding new features) in the near future.
